# Generated by Django 4.2.11 on 2024-03-22 00:10

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_postpagecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='home.category'),
        ),
        migrations.DeleteModel(
            name='PostPageCategory',
        ),
    ]
